import { evaluate, network, type Network } from "../demo.ts";
import type { MissionState } from "./model.ts";
export type Role="citizen"|"researcher";
export type ChapterId="opening"|"process"|"citizen"|"carry"|"researcher"|"check"|"outreach"|"followup"|"case"|"next";
export interface Chapter {id:ChapterId;title:string;role:Role;caption:string;seconds:number;target:string;expected:string;guard:(s:MissionState,data:Network)=>boolean;engineSelector:"count"|"recommendation"|"status";autoplay:readonly string[];}
const reviewed=(s:MissionState,index:number)=>{const report=s.reports[index];return !!report&&s.evidence.decisions.some(d=>d.report_id===report.id&&d.state!=="unreviewed");};
export const timeline:readonly Chapter[]=[
  {id:"opening",title:"Follow the foam",role:"citizen",caption:"See how a small change in a stream can start a shared investigation.",seconds:12,target:"opening",expected:"See the story behind the observation",guard:()=>true,engineSelector:"count",autoplay:[]},
  {id:"process",title:"A shared investigation",role:"researcher",caption:"Follow the four steps: notice, review, narrow the search and check again.",seconds:10,target:"process",expected:"Read the four steps",guard:()=>true,engineSelector:"count",autoplay:[]},
  {id:"citizen",title:"You are the citizen",role:"citizen",caption:"Write what you saw at a stream site. The assistant helps with wording; you confirm the report.",seconds:40,target:"report-text",expected:"Confirm and submit your report",guard:s=>s.reports.length>0,engineSelector:"count",autoplay:["example","assistant","answers","confirm","submit"]},
  {id:"carry",title:"Nothing gets lost",role:"researcher",caption:"See the citizen's words and context arrive in the review queue. The search stays unchanged until review.",seconds:16,target:"carry",expected:"Inspect the submitted report",guard:s=>s.reports.length>0,engineSelector:"count",autoplay:[]},
  {id:"researcher",title:"You are the researcher",role:"researcher",caption:"Check the observation and its assumptions. Approving usable evidence narrows the possible stream sections.",seconds:32,target:"review",expected:"Review the observation",guard:(s,d)=>reviewed(s,0)&&evaluate(s.evidence,d).status!=="conflict",engineSelector:"status",autoplay:["context","assumptions","comparable","reason","approve"]},
  {id:"check",title:"Where would you check next?",role:"researcher",caption:"Compare places to check next. Pick the site that best separates the remaining possibilities.",seconds:30,target:"pick",expected:"Find the best next site",guard:(s,d)=>!evaluate(s.evidence,d).recommendation||s.selected===evaluate(s.evidence,d).recommendation?.siteCode,engineSelector:"recommendation",autoplay:["pick","best"]},
  {id:"outreach",title:"Ask for another observation",role:"researcher",caption:"Preview a field-check request in WhatsApp and SMS, with a report link and example volunteer replies. No messages are sent.",seconds:25,target:"task",expected:"Read the mock conversations",guard:()=>true,engineSelector:"recommendation",autoplay:["task"]},
  {id:"followup",title:"One more check",role:"citizen",caption:"Report from the selected site, then review the new observation. Watch how another check changes the search.",seconds:45,target:"report-text",expected:"Submit and review the follow-up",guard:(s,d)=>(!s.selected||reviewed(s,1))&&evaluate(s.evidence,d).status!=="conflict",engineSelector:"count",autoplay:["example","assistant","answers","confirm","submit","context","assumptions","comparable","reason","approve"]},
  {id:"case",title:"Your case file",role:"researcher",caption:"Read the evidence trail and see why the search changed. Download the simulated case for inspection.",seconds:20,target:"case-file",expected:"Read or export the case",guard:()=>true,engineSelector:"status",autoplay:[]},
  {id:"next",title:"What comes next",role:"researcher",caption:"See what a field pilot would need, then choose to replay or explore live reporting.",seconds:10,target:"next",expected:"Explore next steps",guard:()=>true,engineSelector:"status",autoplay:[]},
];
export const canAdvance=(index:number,state:MissionState,data:Network=network)=>timeline[index]!.guard(state,data);
