import { evaluate, network, type Network } from "../demo.ts";
import type { MissionState } from "./model.ts";
export type Role="citizen"|"researcher";
export type ChapterId="opening"|"process"|"citizen"|"carry"|"researcher"|"check"|"outreach"|"followup"|"case"|"next";
export interface Chapter {id:ChapterId;title:string;role:Role;caption:string;seconds:number;target:string;expected:string;guard:(s:MissionState,data:Network)=>boolean;engineSelector:"count"|"recommendation"|"status";autoplay:readonly string[];}
const reviewed=(s:MissionState,index:number)=>{const report=s.reports[index];return !!report&&s.evidence.decisions.some(d=>d.report_id===report.id&&d.state!=="unreviewed");};
export const timeline:readonly Chapter[]=[
  {id:"opening",title:"Follow the foam",role:"citizen",caption:"Foam gathers where the current slows. One observation starts an investigation, but cannot explain its cause.",seconds:12,target:"opening",expected:"Watch or skip",guard:()=>true,engineSelector:"count",autoplay:[]},
  {id:"process",title:"A shared investigation",role:"researcher",caption:"Report what you see. Review the context. Narrow the possibilities. Choose the next useful check.",seconds:10,target:"process",expected:"Read the four steps",guard:()=>true,engineSelector:"count",autoplay:[]},
  {id:"citizen",title:"You are the citizen",role:"citizen",caption:"Describe foam at a site. AI can help draft, but you confirm the observation before a researcher reviews it.",seconds:40,target:"report-text",expected:"Confirm and submit your report",guard:s=>s.reports.length>0,engineSelector:"count",autoplay:["example","assistant","answers","confirm","submit"]},
  {id:"carry",title:"Nothing gets lost",role:"researcher",caption:"Your exact words, draft provenance and context answers arrive together. Pending reports do not change the map.",seconds:16,target:"carry",expected:"Inspect the submitted report",guard:s=>s.reports.length>0,engineSelector:"count",autoplay:[]},
  {id:"researcher",title:"You are the researcher",role:"researcher",caption:"Inspect unknown context and acknowledge the assumptions. Only approved, usable observations can narrow the candidate reaches.",seconds:32,target:"review",expected:"Review the observation",guard:(s,d)=>reviewed(s,0)&&evaluate(s.evidence,d).status!=="conflict",engineSelector:"status",autoplay:["context","assumptions","comparable","reason","approve"]},
  {id:"check",title:"Where would you check next?",role:"researcher",caption:"Choose an accessible site. Compare what Seen and Not seen would leave, then match the engine’s most balanced useful split.",seconds:30,target:"pick",expected:"Find the best next site",guard:(s,d)=>!evaluate(s.evidence,d).recommendation||s.selected===evaluate(s.evidence,d).recommendation?.siteCode,engineSelector:"recommendation",autoplay:["pick","best"]},
  {id:"outreach",title:"Ask for another observation",role:"researcher",caption:"A short task carries the site and engine facts to fictional volunteers. These messages illustrate a possible workflow.",seconds:25,target:"task",expected:"Read the mock conversation",guard:()=>true,engineSelector:"recommendation",autoplay:["task"]},
  {id:"followup",title:"One more check",role:"citizen",caption:"A second citizen checks the selected site. Confirm their report, then review it with the same evidence rules.",seconds:45,target:"report-text",expected:"Submit and review the follow-up",guard:(s,d)=>(!s.selected||reviewed(s,1))&&evaluate(s.evidence,d).status!=="conflict",engineSelector:"count",autoplay:["example","assistant","answers","confirm","submit","context","assumptions","comparable","reason","approve"]},
  {id:"case",title:"Your case file",role:"researcher",caption:"The complete evidence trail explains every change. A priority reach is a place to investigate, not proof of contamination.",seconds:20,target:"case-file",expected:"Read or export the case",guard:()=>true,engineSelector:"status",autoplay:[]},
  {id:"next",title:"What comes next",role:"researcher",caption:"This simulation ends here. Explore the interactive demo or submit a real observation through the separate reporting flow.",seconds:10,target:"next",expected:"Explore next steps",guard:()=>true,engineSelector:"status",autoplay:[]},
];
export const canAdvance=(index:number,state:MissionState,data:Network=network)=>timeline[index]!.guard(state,data);
